/** @format */

export const categoryColors = {
  Groceries: "#FFD700",
  Rent: "#FF6347",
  Salary: "#32CD32",
  Freelancing: "#6495ED",
  Utilities: "#00CED1",
  Electronics: "#8A2BE2",
  "Dining Out": "#FFA07A",
  "Breakfast Supplies": "#FFDEAD",
  "Household Items": "#F0E68C",
  "Christmas Gifts": "#FF69B4",
  "New Year Party Supplies": "#DB7093",
  "Thanksgiving Groceries": "#CD853F",
  Bonus: "#6B8E23",
  "Consulting Work": "#4682B4",
  "Part-Time Job": "#DAA520",
  "Online Sales": "#20B2AA",
  "Freelance Writing": "#778899",
  "End of Year Bonus": "#5F9EA0",
  "Thanksgiving Freelance": "#BDB76B",
  Default: "#D3D3D3",
};

export const categoryEmojies = {
  Groceries: "🛒",
  Rent: "🏠",
  Salary: "💰",
  Freelancing: "👨🏻‍💻",
  Utilities: "💡",
  Electronics: "🖥️",
  "Dining Out": "🍽️",
  "Breakfast Supplies": "🥐",
  "Household Items": "🏡",
  "Christmas Gifts": "🎁",
  "New Year Party Supplies": "🎉",
  "Thanksgiving Groceries": "🦃",
  Bonus: "🎊",
  "Consulting Work": "💼",
  "Part-Time Job": "⌚",
  "Online Sales": "🛒",
  "Freelance Writing": "✍️",
  "End of Year Bonus": "🍾",
  "Thanksgiving Freelance": "🍂",
  Default: "🫰🏼",
};
